# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoCientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Artigo científico',
                'verbose_name_plural': 'Artigos científicos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('eventoPrincipal', models.CharField(max_length=100, null=True, verbose_name='Evento principal')),
                ('sigla', models.CharField(max_length=2, null=True)),
                ('dataEHoraDeInicio', models.DateTimeField(null=True, verbose_name='Data e hora de início')),
                ('palavraChave', models.CharField(max_length=100, null=True, verbose_name='Palavra chave')),
                ('logoTipo', models.CharField(max_length=150, null=True, verbose_name='Logo tipo')),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('uf', models.CharField(max_length=2, null=True)),
                ('endereco', models.CharField(max_length=100, null=True, verbose_name='Endereço')),
                ('cep', models.CharField(max_length=8, null=True, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.Pessoa')),
                ('curriculo', models.TextField()),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
            bases=('eventos.pessoa',),
        ),
        migrations.CreateModel(
            name='EventoCientifico',
            fields=[
                ('evento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.Evento')),
                ('issn', models.CharField(max_length=100, verbose_name='ISSN')),
            ],
            options={
                'verbose_name': 'Evento científico',
                'verbose_name_plural': 'Eventos científicos',
            },
            bases=('eventos.evento',),
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.Pessoa')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
            ],
            options={
                'verbose_name': 'Pessoa física',
                'verbose_name_plural': 'Pessoas físicas',
            },
            bases=('eventos.pessoa',),
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.Pessoa')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('razaoSocial', models.CharField(max_length=100, null=True, verbose_name='Razão social')),
            ],
            options={
                'verbose_name': 'Pessoa jurídica',
                'verbose_name_plural': 'Pessoas jurídicas',
            },
            bases=('eventos.pessoa',),
        ),
        migrations.AddField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='eventos.Pessoa'),
        ),
        migrations.AddField(
            model_name='artigocientifico',
            name='evento',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='artigoCientifico', to='eventos.EventoCientifico'),
        ),
    ]
